angular.module(
    'eu.myclimateservice.csis.scenario-analysis.demoApp.controllers',
    [
        'de.cismet.crisma.ICMM.config',
        'de.cismet.crisma.ICMM.Worldstates',
        'de.cismet.cids.rest.collidngNames.Nodes',
        'de.cismet.crisma.ICMM.services',
    ]
    );
angular.module(
    'eu.myclimateservice.csis.scenario-analysis.controllers',
    [
        'nvd3ChartDirectives',
        'eu.myclimateservice.csis.scenario-analysis.services',
        'ngDialog',
        'de.cismet.crisma.ICMM.config',
    ]
    );