angular.module(
    'eu.myclimateservice.csis.scenario-analysis.directives',
    [
        'eu.myclimateservice.csis.scenario-analysis.controllers',
        'ngTable',
        'de.cismet.crisma.ICMM.Worldstates',
        'mgcrea.ngStrap.popover'
    ]
);